name: ROS 2 CI

on:
  push:
    branches: [master,feature/pcb_pinout]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        #stores github workspace in $GITHUB_WORKSPACE

      - name: Run build test within docker container
        run:  |
              docker pull dvarx/electrostimulation_fw_build_24_04
              docker run dvarx/electrostimulation_fw_build_24_04